package eventmanagementsystem;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// Imports go AFTER the package
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class DashboardScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardScreen.class.getName());

    /**
     * Creates new form DashboardScreen
     * @param userName
     */
    public DashboardScreen(String userName) {
        initComponents();
        lblWelcome.setText("Welcome, " + userName + "!");
        loadDashboardStats();
    }
    private void loadDashboardStats() {
        try {
            // Total Events
            try (Connection conn = DatabaseConnection.getConnection()) {
                // Total Events
                PreparedStatement st1 = conn.prepareStatement("SELECT COUNT(*) AS total FROM events");
                ResultSet rs1 = st1.executeQuery();
                if(rs1.next()) lblTotalEvents.setText("Total Events: " + rs1.getInt("total"));
                
                // Total Registrations
                PreparedStatement st2 = conn.prepareStatement("SELECT COUNT(*) AS total FROM registrations");
                ResultSet rs2 = st2.executeQuery();
                if(rs2.next()) lblTotalRegs.setText("Total Registrations: " + rs2.getInt("total"));
                
                // Upcoming Events
                PreparedStatement st3 = conn.prepareStatement("SELECT COUNT(*) AS total FROM events WHERE event_date >= CURDATE()");
                ResultSet rs3 = st3.executeQuery();
                if(rs3.next()) lblUpcomingEvents.setText("Upcoming Events: " + rs3.getInt("total"));
                
                // Full Events
                String sqlFull = "SELECT COUNT(*) AS total FROM events e WHERE (SELECT COUNT(*) FROM registrations r WHERE r.event_id = e.event_id) >= e.max_slots";
                PreparedStatement st4 = conn.prepareStatement(sqlFull);
                ResultSet rs4 = st4.executeQuery();
                if(rs4.next()) lblFullEvents.setText("Full Events: " + rs4.getInt("total"));
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblTotalEvents = new javax.swing.JLabel();
        lblTotalRegs = new javax.swing.JLabel();
        lblUpcomingEvents = new javax.swing.JLabel();
        lblFullEvents = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnManageEvents = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setText("Welcome to the Dashboard!");

        lblTotalEvents.setText("jLabel1");

        lblTotalRegs.setText("jLabel1");

        lblUpcomingEvents.setText("jLabel1");

        lblFullEvents.setText("jLabel1");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnManageEvents.setText("Manage Events");
        btnManageEvents.addActionListener(this::btnManageEventsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFullEvents, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(lblTotalRegs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalEvents, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUpcomingEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(212, 212, 212))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnManageEvents)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addGap(27, 27, 27)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(lblTotalEvents)
                .addGap(18, 18, 18)
                .addComponent(lblTotalRegs)
                .addGap(18, 18, 18)
                .addComponent(lblUpcomingEvents)
                .addGap(18, 18, 18)
                .addComponent(lblFullEvents)
                .addGap(48, 48, 48)
                .addComponent(btnManageEvents)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // 1. Show a confirmation dialog box
int confirm = JOptionPane.showConfirmDialog(this, 
    "Are you sure you want to logout?", 
    "Logout Confirmation", 
    JOptionPane.YES_NO_OPTION);

// 2. If the user clicks "Yes"
if (confirm == JOptionPane.YES_OPTION) {
    // Create a new instance of the Login Screen
    LoginScreen login = new LoginScreen();
    
    // Make the Login Screen visible
    login.setVisible(true);
    
    // Close (dispose) the current Dashboard Screen
    this.dispose();
}
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEventsActionPerformed
      EventsScreen manageEvents = new EventsScreen();
      manageEvents.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnManageEventsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardScreen("Admin").setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageEvents;
    private javax.swing.JLabel lblFullEvents;
    private javax.swing.JLabel lblTotalEvents;
    private javax.swing.JLabel lblTotalRegs;
    private javax.swing.JLabel lblUpcomingEvents;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
