/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventmanagementsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Weather Report
 */
public class EventsScreen extends javax.swing.JFrame {

    private int selectedEventId = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EventsScreen.class.getName());

    /**
     * Creates new form EventsScreen
     */
    public EventsScreen() {
        initComponents();
        loadEventsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        btnAddEvent = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Event ID", "Event Name", "Event Date", "Location", "Max Slots"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEvents);
        if (tblEvents.getColumnModel().getColumnCount() > 0) {
            tblEvents.getColumnModel().getColumn(0).setResizable(false);
        }

        btnAddEvent.setText("Add Event");
        btnAddEvent.addActionListener(this::btnAddEventActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddEvent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddEvent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventActionPerformed
        // 1. Create the text fields for the pop-up
        javax.swing.JTextField txtName = new javax.swing.JTextField();
        // Create 3 smaller text boxes (the number inside sets the visual width)
        javax.swing.JTextField txtYear = new javax.swing.JTextField("2026", 4); // Pre-filled with 2026!
        javax.swing.JTextField txtMonth = new javax.swing.JTextField(2);
        javax.swing.JTextField txtDay = new javax.swing.JTextField(2);
        
        // Group them side-by-side in a mini panel with dashes in between
        javax.swing.JPanel datePanel = new javax.swing.JPanel();
        datePanel.add(txtYear);
        datePanel.add(new javax.swing.JLabel("-"));
        datePanel.add(txtMonth);
        datePanel.add(new javax.swing.JLabel("-"));
        datePanel.add(txtDay);
        javax.swing.JTextField txtLoc = new javax.swing.JTextField();
        javax.swing.JTextField txtSlots = new javax.swing.JTextField();

        // 2. Bundle the labels and fields together into an array
        Object[] formFields = {
            "Event Name:", txtName,
            "Event Date (YYYY-MM-DD):", datePanel, // <-- We put the whole panel here!
            "Location:", txtLoc,
            "Max Slots:", txtSlots
        };

        // 3. Trigger the pop-up window
        int result = JOptionPane.showConfirmDialog(this, formFields, "Add New Event", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        // 4. If the user clicks "OK" on the pop-up
        if (result == JOptionPane.OK_OPTION) {

            // Validation: Make sure they didn't leave anything blank
            if (txtName.getText().trim().isEmpty() || txtYear.getText().trim().isEmpty() || txtMonth.getText().trim().isEmpty() || txtDay.getText().trim().isEmpty() || txtLoc.getText().trim().isEmpty() || txtSlots.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Stop the code
            }

            // Save to Database
            try {
                try (java.sql.Connection conn = DatabaseConnection.getConnection()) {
                    String sql = "INSERT INTO events (event_name, event_date, venue, max_slots) VALUES (?, ?, ?, ?)";
                    PreparedStatement stmt = conn.prepareStatement(sql);

                    stmt.setString(1, txtName.getText());
                    
        String formattedDate = txtYear.getText() + "-" + txtMonth.getText() + "-" + txtDay.getText();
        stmt.setString(2, formattedDate);
                    stmt.setString(3, txtLoc.getText());
                    stmt.setInt(4, Integer.parseInt(txtSlots.getText())); // Converts the slot text to an integer

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Event Successfully Added!");
                }

                // Refresh the table instantly to show the new event
                loadEventsTable();

            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error adding event: " + e.getMessage());
            } catch (SQLException ex) {
                System.getLogger(EventsScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_btnAddEventActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        DashboardScreen dash = new DashboardScreen("Admin");
        dash.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // 1. Check if an event was actually selected from the table
        // We use the class-level selectedEventId tracker here!
        if (selectedEventId == 0) {
            JOptionPane.showMessageDialog(this, "Please click on an event in the table first to delete it.");
            return; // Stop the code
        }

        // 2. Ask for confirmation (Safety first!)
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to completely delete this event?", 
                "Confirm Delete", 
                JOptionPane.YES_NO_OPTION);

        // 3. If they click "Yes", execute the SQL
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection conn = (Connection) DatabaseConnection.getConnection();
                
                // The SQL command to delete based on the ID
                String sql = "DELETE FROM events WHERE event_id = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setInt(1, selectedEventId); // Uses your clicked ID!
                
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Event Successfully Deleted!");
                
                // 4. Refresh the table and reset the tracker
                loadEventsTable();
                selectedEventId = 0; // Safely reset it AFTER the delete is completely finished
                
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Error deleting event: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // 1. Check if an event was actually selected from the table
        if (selectedEventId == 0) {
            JOptionPane.showMessageDialog(this, "Please click on an event in the table first to update it.");
            return; // Stop the code
        }

        // 2. Grab the current data directly from the table's selected row
        DefaultTableModel model = (DefaultTableModel) tblEvents.getModel();
        int selectedRowIndex = tblEvents.getSelectedRow();

        String currentName = model.getValueAt(selectedRowIndex, 1).toString();
        String currentDate = model.getValueAt(selectedRowIndex, 2).toString();
        String currentLocation = model.getValueAt(selectedRowIndex, 3).toString();
        String currentSlots = model.getValueAt(selectedRowIndex, 4).toString();

        // 3. Create the text fields for the pop-up and PRE-FILL them with the current data
        javax.swing.JTextField txtName = new javax.swing.JTextField(currentName);
        javax.swing.JTextField txtDate = new javax.swing.JTextField(currentDate);
        javax.swing.JTextField txtLoc = new javax.swing.JTextField(currentLocation);
        javax.swing.JTextField txtSlots = new javax.swing.JTextField(currentSlots);

        // Bundle them up
        Object[] formFields = {
            "Edit Event Name:", txtName,
            "Edit Event Date (YYYY-MM-DD):", txtDate,
            "Edit Location:", txtLoc,
            "Edit Max Slots:", txtSlots
        };

        // 4. Trigger the pop-up window
        int result = JOptionPane.showConfirmDialog(this, formFields, "Update Event", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        // 5. If the user clicks "OK", save the new changes to the database
        if (result == JOptionPane.OK_OPTION) {
            try {
                Connection conn = DatabaseConnection.getConnection();

                // The SQL UPDATE query
                String sql = "UPDATE events SET event_name = ?, event_date = ?, venue = ?, max_slots = ? WHERE event_id = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);

                stmt.setString(1, txtName.getText());
                stmt.setString(2, txtDate.getText());
                stmt.setString(3, txtLoc.getText());
                stmt.setInt(4, Integer.parseInt(txtSlots.getText()));
                stmt.setInt(5, selectedEventId); // We use the hidden ID tracker for the WHERE clause!

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Event Successfully Updated!");


                // Refresh the table and reset the tracker
                loadEventsTable();
                selectedEventId = 0;

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error updating event: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblEventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventsMouseClicked
        // 1. Get the table model and find out which row was clicked
        DefaultTableModel model = (DefaultTableModel) tblEvents.getModel();
        int selectedRowIndex = tblEvents.getSelectedRow();
        
        // 2. Grab the hidden Event ID from the very first column (Column 0)
        selectedEventId = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_tblEventsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EventsScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEvents;
    // End of variables declaration//GEN-END:variables

    private void loadEventsTable() {
        try {
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement stmt = conn.prepareStatement("SELECT * FROM events");
            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tblEvents.getModel();
            model.setRowCount(0); // Wipes the table clean before loading

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("event_id"),
                    rs.getString("event_name"),
                    rs.getDate("event_date"),
                    rs.getString("venue"), 
                    rs.getInt("max_slots")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading table: " + e.getMessage());
        }
    }
}
