/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventmanagementsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class LoginScreen extends javax.swing.JFrame {
    public static String user_name;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginScreen.class.getName());

    // The Ultimate Image Resizer Method
    public void setResponsiveImage(javax.swing.JLabel label, String imagePath) {
        try {
            // 1. Load the original image file
            javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(getClass().getResource(imagePath));
            java.awt.Image img = originalIcon.getImage();

            // 2. Add a listener that perfectly fits the image whenever the label changes size!
            label.addComponentListener(new java.awt.event.ComponentAdapter() {
                @Override
                public void componentResized(java.awt.event.ComponentEvent e) {
                    // Smoothly scale the image to the exact current width and height of the JLabel
                    java.awt.Image scaledImg = img.getScaledInstance(label.getWidth(), label.getHeight(), java.awt.Image.SCALE_SMOOTH);
                    label.setIcon(new javax.swing.ImageIcon(scaledImg));
                }
            });
            
        } catch (Exception e) {
            System.out.println("Could not find the image at: " + imagePath);
        }
    }
    
    
    public LoginScreen() {
       initComponents();
       
  
       this.setLocationRelativeTo(null); // Keeps the window centered on your screen
        
        // Ensure the backgrounds are transparent so your Synthwave purple shows!
        pnlLogin.setOpaque(false);
        pnlSignup.setOpaque(false);
        
        // Force the app to show the Login screen first when it boots up
        java.awt.CardLayout card = (java.awt.CardLayout) jPanel2.getLayout();
        card.show(jPanel2, "LOGIN");
       
        java.awt.Color pressedColor = new java.awt.Color(153, 153, 153);
        java.awt.Color originalColor = new java.awt.Color(192, 192, 192);
        
        javax.swing.border.Border raisedBorder = new javax.swing.border.BevelBorder(
        javax.swing.border.BevelBorder.RAISED, 
        java.awt.Color.WHITE, java.awt.Color.WHITE, 
        java.awt.Color.BLACK, java.awt.Color.BLACK
    );

    // 2. LOGIN BUTTON EFFECT
    btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            btnLogin.setBackground(pressedColor);
        }
        @Override
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            btnLogin.setBorder(raisedBorder);
            btnLogin.setBackground(originalColor);
        }
    });

    // 3. SIGN UP BUTTON EFFECT
    btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            btnSignUp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            btnSignUp.setBackground(pressedColor);
        }
        @Override
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            btnSignUp.setBorder(raisedBorder);
            btnSignUp.setBackground(originalColor);
        }
    });
}
     
        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblStar = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        chkPassword = new javax.swing.JCheckBox();
        btnSignUp = new javax.swing.JToggleButton();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblloginbg1 = new javax.swing.JLabel();
        pnlSignup = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblStar2 = new javax.swing.JLabel();
        lblWelcome2 = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JToggleButton();
        btnBackToLogin = new javax.swing.JButton();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        lblPassword1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtUsername1 = new javax.swing.JTextField();
        chkPassword1 = new javax.swing.JCheckBox();
        lblUsername1 = new javax.swing.JLabel();
        lblsignupbg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Events Management System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1001, 657));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(106, 0, 102));
        jPanel2.setLayout(new java.awt.CardLayout());

        pnlLogin.setBackground(new java.awt.Color(147, 71, 144));
        pnlLogin.setAlignmentX(0.0F);
        pnlLogin.setAlignmentY(0.0F);
        pnlLogin.setMinimumSize(new java.awt.Dimension(1001, 657));
        pnlLogin.setPreferredSize(new java.awt.Dimension(1001, 657));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Welcome.png"))); // NOI18N
        pnlLogin.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, 90));

        lblStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star-ezgif.com-resize.gif"))); // NOI18N
        pnlLogin.add(lblStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 360, 190));

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logicore-ezgif.com-resize.gif"))); // NOI18N
        pnlLogin.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 770, 280));

        lblUsername.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        pnlLogin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        chkPassword.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        chkPassword.setForeground(new java.awt.Color(255, 255, 255));
        chkPassword.setText("Show Password");
        chkPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        chkPassword.addActionListener(this::chkPasswordActionPerformed);
        pnlLogin.add(chkPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, 32));

        btnSignUp.setBackground(new java.awt.Color(204, 204, 255));
        btnSignUp.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        btnSignUp.setContentAreaFilled(false);
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.setFocusPainted(false);
        btnSignUp.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSignUp.setMaximumSize(new java.awt.Dimension(47, 24));
        btnSignUp.setMinimumSize(new java.awt.Dimension(47, 24));
        btnSignUp.setOpaque(true);
        btnSignUp.setPreferredSize(new java.awt.Dimension(72, 33));
        btnSignUp.addActionListener(this::btnSignUpActionPerformed);
        pnlLogin.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 140, -1));

        txtUsername.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        pnlLogin.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 308, 30));

        lblPassword.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password ");
        pnlLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        txtPassword.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        pnlLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 308, 30));

        btnLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnLogin.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setFocusPainted(false);
        btnLogin.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnLogin.setOpaque(true);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 140, 33));

        lblloginbg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblloginbg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login and signin.png"))); // NOI18N
        pnlLogin.add(lblloginbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -10, 1090, 680));

        jPanel2.add(pnlLogin, "LOGIN");

        pnlSignup.setToolTipText("");
        pnlSignup.setAutoscrolls(true);
        pnlSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSignup.setMinimumSize(new java.awt.Dimension(1001, 657));
        pnlSignup.setPreferredSize(new java.awt.Dimension(1001, 657));
        pnlSignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logicore-ezgif.com-resize.gif"))); // NOI18N
        pnlSignup.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 770, 280));

        lblStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star-ezgif.com-resize.gif"))); // NOI18N
        pnlSignup.add(lblStar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 360, 190));

        lblWelcome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Welcome.png"))); // NOI18N
        pnlSignup.add(lblWelcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, 90));

        btnCreateAccount.setBackground(new java.awt.Color(204, 204, 255));
        btnCreateAccount.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        btnCreateAccount.setContentAreaFilled(false);
        btnCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAccount.setFocusPainted(false);
        btnCreateAccount.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCreateAccount.setMaximumSize(new java.awt.Dimension(47, 24));
        btnCreateAccount.setMinimumSize(new java.awt.Dimension(47, 24));
        btnCreateAccount.setOpaque(true);
        btnCreateAccount.setPreferredSize(new java.awt.Dimension(72, 33));
        btnCreateAccount.addActionListener(this::btnCreateAccountActionPerformed);
        pnlSignup.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 160, -1));

        btnBackToLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnBackToLogin.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnBackToLogin.setText("Back to Login");
        btnBackToLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        btnBackToLogin.setContentAreaFilled(false);
        btnBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackToLogin.setFocusPainted(false);
        btnBackToLogin.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnBackToLogin.setOpaque(true);
        btnBackToLogin.addActionListener(this::btnBackToLoginActionPerformed);
        pnlSignup.add(btnBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 140, 33));

        lblFirstName.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");
        pnlSignup.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 100, -1));

        lblLastName.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");
        pnlSignup.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 100, -1));

        txtPassword1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtPassword1.addActionListener(this::txtPassword1ActionPerformed);
        pnlSignup.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 158, -1));

        lblPassword1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Password");
        pnlSignup.add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 100, -1));

        txtLastName.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pnlSignup.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 158, -1));

        txtFirstName.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtFirstName.addActionListener(this::txtFirstNameActionPerformed);
        pnlSignup.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 158, -1));

        txtUsername1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pnlSignup.add(txtUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 158, -1));

        chkPassword1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        chkPassword1.setForeground(new java.awt.Color(255, 255, 255));
        chkPassword1.setText("Show Password");
        chkPassword1.addActionListener(this::chkPassword1ActionPerformed);
        pnlSignup.add(chkPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 160, 32));

        lblUsername1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setText("Username");
        pnlSignup.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 100, -1));

        lblsignupbg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login and signin.png"))); // NOI18N
        lblsignupbg2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSignup.add(lblsignupbg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        jPanel2.add(pnlSignup, "SIGNUP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
 // 1. GET THE TEXT (This creates the 'username' and 'password' variables!)
    String username = txtUsername.getText();
    String password = new String(txtPassword.getPassword()); 

    // 2. Quick check: Did they leave it blank?
    if (username.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter both your username and password.", "Missing Info", javax.swing.JOptionPane.WARNING_MESSAGE);
        return; 
    }

    // 3. SET THE TRACKER (This creates the 'loginSuccessful' variable!)
    boolean loginSuccessful = false; 

    // 4. THE DATABASE BLOCK
    try {
        java.sql.Connection conn = DatabaseConnection.getConnection();
        
        if (conn != null) {
            java.sql.PreparedStatement pst = conn.prepareStatement("SELECT * FROM users WHERE BINARY username = ? AND BINARY  password = ?");
            
            // Now Java knows what these variables are because they were declared at the top!
            pst.setString(1, username);
            pst.setString(2, password);
            
            java.sql.ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                 // Now Java knows what this variable is!
                 loginSuccessful = true; 
            }
            
            rs.close();
            pst.close();
            conn.close();
            
        } else {
            return; 
        }

    } catch (java.sql.SQLException sqlErr) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error checking user credentials.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // 5. THE UI TRANSITION BLOCK
        if (loginSuccessful) {
            try {
                System.out.println("Login Success! Attempting to build the Attendee Portal...");

                // You are passing 'username' into the AttendeePortal constructor
                AttendeePortal nextScreen = new AttendeePortal(username);

                nextScreen.setVisible(true); // Shows the new window
                this.dispose(); 
            
        } catch (Exception uiErr) {
            System.out.println("CRASH DURING SCREEN BUILD!");
            javax.swing.JOptionPane.showMessageDialog(this, "UI Error: A file or image on the Attendee Portal is missing!", "Screen Load Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid Username or Password.", "Login Failed", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
// Grab the CardLayout manager from your main stage (jPanel2)
        java.awt.CardLayout card = (java.awt.CardLayout) jPanel2.getLayout();
        
        // Tell it to flip to the card named "SIGNUP"
        card.show(jPanel2, "SIGNUP");
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnLogin.doClick(); // This magically clicks your Login button for them!
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void chkPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordActionPerformed
        if (chkPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0); // Shows the real letters
        } else {
            txtPassword.setEchoChar('*'); // Hides them again (or use • if you prefer!)
        }
    }//GEN-LAST:event_chkPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void chkPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPassword1ActionPerformed
       
    if (chkPassword1.isSelected()) {
       
        txtPassword.setEchoChar((char) 0);
        txtPassword1.setEchoChar((char) 0);
    } else {
        
        txtPassword.setEchoChar('\u2022'); 
        txtPassword1.setEchoChar('\u2022');
    }
    }//GEN-LAST:event_chkPassword1ActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword1ActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
// 1. Updated Validation Check (Notice the '1' on Username and Password)
        if (txtFirstName.getText().trim().isEmpty() ||
            txtLastName.getText().trim().isEmpty() ||
            txtUsername1.getText().trim().isEmpty() || 
            String.valueOf(txtPassword1.getPassword()).trim().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
            return;
        }

        try {
            java.sql.Connection conn = DatabaseConnection.getConnection();

            String sql = "INSERT INTO users (first_name, last_name, username, password, role) VALUES (?, ?, ?, ?, 'Attendee')";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);

            // 2. Updated Database Save (Notice the '1' on Username and Password)
            stmt.setString(1, txtFirstName.getText().trim());
            stmt.setString(2, txtLastName.getText().trim());
            stmt.setString(3, txtUsername1.getText().trim()); 
            stmt.setString(4, String.valueOf(txtPassword1.getPassword())); 

            stmt.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this, "Account Created Successfully! You can now log in.");

            // Kick them back to the Login Screen
            LoginScreen login = new LoginScreen(); 
            login.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Real Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    public LoginScreen(String username) {
        initComponents();
        
        // Feed it the exact variable name of your JLabel, and the exact path to your image!
        
        
        // You can reuse this for as many images as you want!
        // setResponsiveImage(lblLogo, "/Images/my_logo.png");
        
        // ... the rest of your startup code ...
    }
    
    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        // Grab the CardLayout manager from your main stage (jPanel2)
        java.awt.CardLayout card = (java.awt.CardLayout) jPanel2.getLayout();
        
        // Tell it to flip back to the card named "LOGIN"
        card.show(jPanel2, "LOGIN");
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JToggleButton btnCreateAccount;
    private javax.swing.JButton btnLogin;
    private javax.swing.JToggleButton btnSignUp;
    private javax.swing.JCheckBox chkPassword;
    private javax.swing.JCheckBox chkPassword1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblStar;
    private javax.swing.JLabel lblStar2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcome2;
    private javax.swing.JLabel lblloginbg1;
    private javax.swing.JLabel lblsignupbg2;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlSignup;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
