/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventmanagementsystem;

/**
 *
 * @author Weather Report
 */
public class RegistrationScreen extends javax.swing.JFrame {
    
    // 1. Your HashMap sits right at the top
    private java.util.HashMap<String, Integer> eventMap = new java.util.HashMap<>();

    // 2. Your Constructor (The Welcome Mat)
 

    // 3. Your Method MUST start exactly here: outside the constructor's closing brace '}'!
    private void loadEventsDropdown() {
        try {
            java.sql.Connection conn = DatabaseConnection.getConnection();
            
            String sql = "SELECT event_id, event_name FROM events";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            java.sql.ResultSet rs = stmt.executeQuery();
            
            cmbEvents.removeAllItems(); 
            eventMap.clear(); 
            
            while (rs.next()) {
                int id = rs.getInt("event_id");
                String name = rs.getString("event_name");
                
                cmbEvents.addItem(name); 
                eventMap.put(name, id);  
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading dropdown: " + e.getMessage());
        }
    }
    
    private void loadAttendeesTable(int eventId) {
        try {
            // 1. Get the table model and wipe out the 4 ghost rows instantly
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblAttendees.getModel();
            model.setRowCount(0); 

            java.sql.Connection conn = DatabaseConnection.getConnection();
            
            // 2. Only grab attendees that match the currently selected event
            String sql = "SELECT * FROM registrations WHERE event_id = ?";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, eventId);
            java.sql.ResultSet rs = stmt.executeQuery();
            
            // 3. Fill the table with the real data
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("registration_id"),
                    rs.getString("first_name"),
                    rs.getString("last_name"),
                    rs.getString("email"),
                    rs.getString("contact_number"),
                    rs.getString("attendance_status"),
                    rs.getTimestamp("registered_at")
                });
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading roster: " + e.getMessage());
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationScreen.class.getName());

    /**
     * Creates new form RegistrationScreen
     */
    public RegistrationScreen() {
        initComponents();
        loadEventsDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbEvents = new javax.swing.JComboBox<>();
        txtFirstName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendees = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbEvents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEvents.addItemListener(this::cmbEventsItemStateChanged);
        cmbEvents.addActionListener(this::cmbEventsActionPerformed);

        jButton1.setText("Register");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        tblAttendees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Reg ID", "First Name", "Last Name", "Email", "Contact No.", "Status", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAttendees);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblEmail.setText("Email");

        lblContact.setText("Contact #No.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEvents, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContact)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(176, 176, 176))
                            .addComponent(txtEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(223, 223, 223))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(44, 44, 44)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(60, 60, 60))
                                    .addComponent(txtLastName))))))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnBack)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbEvents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail)
                        .addGap(2, 2, 2)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblContact)
                        .addGap(1, 1, 1)
                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEventsActionPerformed
        
    }//GEN-LAST:event_cmbEventsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // 1. Safety Check: Make sure they didn't leave any boxes blank!
        if (txtFirstName.getText().trim().isEmpty() || 
            txtLastName.getText().trim().isEmpty() || 
            txtEmail.getText().trim().isEmpty() || 
            txtContact.getText().trim().isEmpty()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all attendee details!");
            return; 
        }

        if (cmbEvents.getSelectedItem() == null) return;
        String selectedEventName = cmbEvents.getSelectedItem().toString();
        Integer eventId = eventMap.get(selectedEventName);

        if (eventId != null) {
            try {
                java.sql.Connection conn = DatabaseConnection.getConnection();
                
                // --- THE BOUNCER: SLOT ENFORCEMENT LOGIC ---
                
                // A. Find out the maximum slots allowed for this specific event
                java.sql.PreparedStatement maxStmt = conn.prepareStatement("SELECT max_slots FROM events WHERE event_id = ?");
                maxStmt.setInt(1, eventId);
                java.sql.ResultSet maxRs = maxStmt.executeQuery();
                int maxSlots = 0;
                if (maxRs.next()) {
                    maxSlots = maxRs.getInt("max_slots");
                }
                
                // B. Count how many people are currently registered
                java.sql.PreparedStatement countStmt = conn.prepareStatement("SELECT COUNT(*) AS total FROM registrations WHERE event_id = ?");
                countStmt.setInt(1, eventId);
                java.sql.ResultSet countRs = countStmt.executeQuery();
                int currentRegistrations = 0;
                if (countRs.next()) {
                    currentRegistrations = countRs.getInt("total");
                }
                
                // C. The strict cutoff!
                if (currentRegistrations >= maxSlots) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Registration Failed: This event is fully booked! (Limit: " + maxSlots + ")");
                    return; // Stop the code right here, do NOT save them to the database
                }
                
                // --- END OF THE BOUNCER ---

                // If they passed the bouncer, officially register them!
                String sql = "INSERT INTO registrations (event_id, first_name, last_name, email, contact_number, attendance_status) VALUES (?, ?, ?, ?, ?, ?)";
                java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
                
                stmt.setInt(1, eventId);
                stmt.setString(2, txtFirstName.getText().trim());
                stmt.setString(3, txtLastName.getText().trim());
                stmt.setString(4, txtEmail.getText().trim());
                stmt.setString(5, txtContact.getText().trim());
                stmt.setString(6, "Registered"); 
                
                stmt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Attendee Successfully Registered!");
                
                // Wipe the text boxes clean
                txtFirstName.setText("");
                txtLastName.setText("");
                txtEmail.setText("");
                txtContact.setText("");
                
                // Refresh the table
                loadAttendeesTable(eventId);
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error registering attendee: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        DashboardScreen dash = new DashboardScreen("Admin");
        dash.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbEventsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEventsItemStateChanged
         // This ensures the code only runs AFTER the ComboBox has fully, visually changed to your new click!
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            
            if (cmbEvents.getSelectedItem() != null) {
                String selectedEventName = cmbEvents.getSelectedItem().toString();
                Integer eventId = eventMap.get(selectedEventName);
                
                if (eventId != null) {
                    loadAttendeesTable(eventId); 
                }
            }
        }
    }//GEN-LAST:event_cmbEventsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbEvents;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JTable tblAttendees;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
